[pytest]
testpaths = ["tests"]
addopts = ["-rf", "-rx", "--disable-pytest-warnings"]
log_cli = false
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
log_level = "INFO"
log_format = "%(asctime)s | %(name)s | %(levelname)s | %(message)s"