"""General configuration for the omop graph, including envrionment variables."""

# DB connection for OMOP CDM database
ENV_OMOP_CDM_DB_URL = "OMOP_CDM_DB_URL"
ENV_OMOP_CDM_DB_USER = "OMOP_CDM_DB_USER"
ENV_OMOP_CDM_DB_PASSWORD = "OMOP_CDM_DB_PASSWORD"
ENV_OMOP_CDM_DB_HOST = "OMOP_CDM_DB_HOST"
ENV_OMOP_CDM_DB_PORT = "OMOP_CDM_DB_PORT"
ENV_OMOP_CDM_DB_NAME = "OMOP_CDM_DB_NAME"
ENV_OMOP_CDM_DB_DRIVER = "OMOP_CDM_DB_DRIVER"

# Ingestion
ENV_OMOP_VOCABULARY_DIR = "OMOP_VOCABULARY_DIR"